//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dhaka_Fiber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bandwidth_Plans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bandwidth_Plans()
        {
            this.Plans = new HashSet<Plan>();
        }
    
        public int Id { get; set; }
        public string Bandwidth_Name { get; set; }
        public string Rate_Download { get; set; }
        public string Rate_Upload { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan> Plans { get; set; }
    }
}
