//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dhaka_Fiber.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dhaka_FiberDbContext : DbContext
    {
        public Dhaka_FiberDbContext()
            : base("name=Dhaka_FiberDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bandwidth_Plans> Bandwidth_Plans { get; set; }
        public virtual DbSet<IP_Pools> IP_Pools { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Router> Routers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Technician> Technicians { get; set; }
        public virtual DbSet<Technician_Experties> Technician_Experties { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
