//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dhaka_Fiber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IP_Pools
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IP_Pools()
        {
            this.Plans = new HashSet<Plan>();
        }
    
        public int Id { get; set; }
        public string Pool_Name { get; set; }
        public string IP_Range { get; set; }
        public string Router { get; set; }
        public string Reamaks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan> Plans { get; set; }
    }
}
