//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dhaka_Fiber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Plan_Name { get; set; }
        public int Bandwidth_Name { get; set; }
        public string Plan_Price { get; set; }
        public int Plan_Validity { get; set; }
        public string Plan_Validity_d_m { get; set; }
        public string Connection_Type { get; set; }
        public int Shared_Users { get; set; }
        public int Router { get; set; }
        public int IP_Pools { get; set; }
    
        public virtual Bandwidth_Plans Bandwidth_Plans { get; set; }
        public virtual IP_Pools IP_Pools1 { get; set; }
        public virtual Router Router1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
