//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dhaka_Fiber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technician
    {
        public string ID { get; set; }
        public int Role { get; set; }
        public string Login_Name { get; set; }
        public string Password { get; set; }
        public string Full_Name { get; set; }
        public int NID { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public int Experties { get; set; }
        public string Address { get; set; }
    
        public virtual Technician_Experties Technician_Experties { get; set; }
        public virtual User_Role User_Role { get; set; }
    }
}
